from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse, HTMLResponse, Response
from pydantic import BaseModel
from analyzer import analyze_email, EmailAnalysisResult, hlr_lookup, HLRResult, sherlock_search, SherlockResult
import os

app = FastAPI(title="Email Analyzer")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class EmailRequest(BaseModel):
    email: str


class PhoneRequest(BaseModel):
    phone: str
    api_key: str = ""


class UsernameRequest(BaseModel):
    username: str


@app.post("/api/analyze", response_model=EmailAnalysisResult)
async def analyze(request: EmailRequest):
    if not request.email or "@" not in request.email:
        raise HTTPException(status_code=400, detail="Invalid email format")
    return await analyze_email(request.email)


@app.post("/api/hlr", response_model=HLRResult)
async def hlr(request: PhoneRequest):
    if not request.phone:
        raise HTTPException(status_code=400, detail="Phone number required")
    return await hlr_lookup(request.phone, request.api_key)


@app.post("/api/sherlock", response_model=SherlockResult)
async def sherlock(request: UsernameRequest):
    if not request.username:
        raise HTTPException(status_code=400, detail="Username required")
    return await sherlock_search(request.username)


@app.post("/api/sherlock/export")
async def sherlock_export(request: UsernameRequest):
    if not request.username:
        raise HTTPException(status_code=400, detail="Username required")

    result = await sherlock_search(request.username)

    found_rows = ""
    for item in result.found:
        found_rows += f'<tr><td>{item["site"]}</td><td><a href="{item["url"]}" target="_blank">{item["url"]}</a></td></tr>\n'

    not_found_html = ", ".join(result.not_found) if result.not_found else "None"

    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Nick Search Report — {result.username}</title>
<style>
body {{ font-family: Arial, sans-serif; background: #0a0a0a; color: #e5e5e5; padding: 40px; }}
h1 {{ color: #22c55e; border-bottom: 2px solid #333; padding-bottom: 10px; }}
h2 {{ color: #3b82f6; margin-top: 30px; }}
table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
th {{ background: #1a1a1a; padding: 10px; text-align: left; border: 1px solid #333; }}
td {{ padding: 8px 10px; border: 1px solid #333; }}
a {{ color: #3b82f6; }}
.stats {{ background: #141414; padding: 15px; border-radius: 8px; margin: 20px 0; }}
.stat {{ margin: 5px 0; }}
.label {{ color: #888; }}
.value {{ color: #fff; font-weight: bold; }}
.not-found {{ color: #666; font-size: 12px; margin-top: 10px; }}
</style>
</head>
<body>
<h1>Nick Search Report</h1>
<div class="stats">
<div class="stat"><span class="label">Username:</span> <span class="value">{result.username}</span></div>
<div class="stat"><span class="label">Found:</span> <span class="value" style="color:#22c55e">{len(result.found)} accounts</span></div>
<div class="stat"><span class="label">Not Found:</span> <span class="value" style="color:#ef4444">{len(result.not_found)} sites</span></div>
<div class="stat"><span class="label">Search Time:</span> <span class="value">{result.search_time}s</span></div>
</div>
<h2>Found Accounts ({len(result.found)})</h2>
<table>
<tr><th>SITE</th><th>LINK</th></tr>
{found_rows}
</table>
<div class="not-found"><h2>Not Found</h2><p>{not_found_html}</p></div>
<p style="margin-top:30px;color:#444;font-size:11px">Generated by SOSINT Email Analyzer</p>
</body>
</html>"""

    return Response(
        content=html,
        media_type="text/html",
        headers={"Content-Disposition": f'attachment; filename="nick_report_{result.username}.html"'}
    )


@app.get("/api/auth/status")
async def auth_status():
    from auth import get_credentials
    creds = get_credentials()
    return {"authenticated": creds is not None and creds.valid}


@app.get("/api/auth/url")
async def auth_url():
    from google_auth_oauthlib.flow import InstalledAppFlow
    credentials_path = os.path.join(os.path.dirname(__file__), 'credentials.json')
    if not os.path.exists(credentials_path):
        return {"error": "credentials.json not found", "url": None}
    flow = InstalledAppFlow.from_client_secrets_file(
        credentials_path,
        ['https://www.googleapis.com/auth/userinfo.profile']
    )
    auth_url, _ = flow.authorization_url(prompt='consent')
    return {"url": auth_url}


@app.get("/api/auth/callback")
async def auth_callback(code: str = None):
    if not code:
        return HTMLResponse("<h1>Error: No code provided</h1>")
    return HTMLResponse("<h1>Authorization complete! You can close this window.</h1>")


@app.get("/api/health")
async def health():
    return {"status": "ok"}


frontend_dir = os.path.join(os.path.dirname(__file__), "..", "frontend")
app.mount("/static", StaticFiles(directory=frontend_dir), name="static")


@app.get("/")
async def serve_frontend():
    return FileResponse(os.path.join(frontend_dir, "index.html"))


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8000)
